-- Migration: fix_teams_code_unique
-- Created: 2026-04-17
-- Purpose: Replace the global UNIQUE constraint on teams.code with a
--          per-competition uniqueness constraint: (code, competition_id).
--          This allows the same team code (e.g. "G2") to exist in LEC
--          and LCK simultaneously once multi-liga support is active.
--
-- Rollback:
--   ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_code_competition_unique;
--   ALTER TABLE teams ADD CONSTRAINT teams_code_key UNIQUE (code);

-- === FORWARD MIGRATION ===

-- 1. Drop the existing global UNIQUE constraint on teams.code.
--    Name is `teams_code_key` — generated by Postgres for the inline
--    UNIQUE keyword on the `code` column in 20260314100000_series_games_schema.sql.
ALTER TABLE teams
  DROP CONSTRAINT IF EXISTS teams_code_key;

-- 2. Add the scoped uniqueness constraint: unique per competition.
ALTER TABLE teams
  ADD CONSTRAINT teams_code_competition_unique UNIQUE (code, competition_id);
